### ISSUE TITLE
Lab 5 - "Lab 2 - Explore with Spark.ipynb"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#100]
Suggestion: I think this file can be removed from the lab instructions folder for simplicity, as it's used in the lab from a different location in GitHub.

**Comment by ctesta-oneillmsft** [comment]
It is in by design

**Comment by VitalyMCT** [comment]
For any issue closed "by design" such as this one, can the MCT community please get a few words in the way of an explanation?
