### ISSUE TITLE
Module 05 | Exercise 4

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#104]
In module 05, Exercise 04 https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure/tree/main/Instructions/Labs/05 the following error has been encountered:

![image](https://user-images.githubusercontent.com/35786030/120015231-b8286c80-bfa8-11eb-91d6-b7ccd14431d8.png)

No work around solution has been found.

**Comment by joelhulen** [comment]
Is the dedicated SQL pool running, or is it paused? You will receive this error if the pool is paused.

**Comment by berkenbrack** [comment]
No errors on the second run through. Thank you Joel for advising.
