### ISSUE TITLE
Lab 3 whiteboard

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#105]
The instructions for Lab 3 talk about an included whiteboard and still havent seen it. Is there a link or video reference into how this lab is conducted? What is described is vague and had an incredibly hard time getting discussion started around what is presented here.

**Comment by ctesta-oneillmsft** [comment]
the references to the board have now been removed
