### ISSUE TITLE
Lab 4 RBAC permissions

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#106]
In the last steps of the lab, even when switching to the history-owners group does not allow write permissions. I have gone through this 3 times and still can't write to the file after following the instructions.

My thought is that there is still a reader role applied to the same email set earlier and you are not asked to remove that role. Following least privilege rules, even if I am part of the owner group, I am still part of the reader group - hence not able to write. I did, however remove the reader group from the ADLS and still could not write.  Literally had to remove the owner group, reader group and reassign my email as a blob storage owner role (essentially undoing everything in order to successfully write.

**Comment by joelhulen** [comment]
I've had this happen. Basically, your system is hanging on to the token that has the claims set based on the previous permissions. Try opening a new in-private/incognito browser session (even with another browser type), sign in, then try writing again. Unfortunately, permissions changes sometimes require this, but not always.

**Comment by Jason-M-Richards** [comment]
Got it, Ill make a note for the next delivery.

**Comment by VitalyMCT** [comment]
Would it be possible to please add some instructions around this scenario, so if students (and/or MCTs!) run into it they would know what to do?
