### ISSUE TITLE
Module 16 - Simplify SQL query

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#108]
Regarding

> In the Power Query editor, open the settings page of the Source step in the query. Expand the Advanced options section, paste the following query and click OK.

I think the query can be simplified to just the nested subquery. The parent's SELECT * was only needed because the check in Synapse a few steps prior was doing SELECT COUNT(*).

**Comment by ctesta-oneillmsft** [comment]
please provide the full example of how it should be rewritten so we can validate

**Comment by VitalyMCT** [comment]
```sql
SELECT
        FS.CustomerID
        ,P.Seasonality
        ,D.Year
        ,D.Quarter
        ,D.Month
        ,avg(FS.TotalAmount) as AvgTotalAmount
        ,avg(FS.ProfitAmount) as AvgProfitAmount
        ,sum(FS.TotalAmount) as TotalAmount
        ,sum(FS.ProfitAmount) as ProfitAmount
    FROM
        wwi.SaleSmall FS
        JOIN wwi.Product P ON P.ProductId = FS.ProductId
        JOIN wwi.Date D ON FS.TransactionDateId = D.DateId
    GROUP BY
        FS.CustomerID
        ,P.Seasonality
        ,D.Year
        ,D.Quarter
        ,D.Month
```

**Comment by ctesta-oneillmsft** [comment]
Thanks, we will update the source files soon,

**Comment by ctesta-oneillmsft** [comment]
resolved
