### ISSUE TITLE
Module 01 - Running notebook

### ISSUE THREAD

**Issue by shirivo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#109]
Explain how start cluster and run the notebook. Also, mention that don't execute all commands at a same time because the streaming jobs need to initialize. 
If you run all commands, you get all these issues that can confuse the learners:
![image](https://user-images.githubusercontent.com/620849/120724893-f2ef4080-c491-11eb-89df-17dd5df9dd2e.png)

For example, this error said is because a incompatible format but the real reason is streaming is not initialized.
![image](https://user-images.githubusercontent.com/620849/120725071-59745e80-c492-11eb-810f-405f6cf9adb4.png)

#shirivo #dp-203

**Comment by ctesta-oneillmsft** [comment]
Trainers can explain this during the course, there are some instructions that advise this, but if we put this in for every single command then we will also be told to remove some of them
