### ISSUE TITLE
Query results different. 

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#11]
"Please note that there are no data results for this query. You should see messages similar to the following:"
The picture depicted is not what I see when I execute the query. 
![image](https://user-images.githubusercontent.com/38757647/116370823-0e1fbe00-a80b-11eb-83ce-a8bbcab66f45.png)

**Comment by joelhulen** [comment]
I updated this just to say that there are no results after running the query.
