### ISSUE TITLE
Module 01 - Starting Azure Databricks

### ISSUE THREAD

**Issue by shirivo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#110]
When you launch the workspace - just first time - you receive this error that can alarm our learners. 
To avoid extra steps verifying roles by the students, I suggest adding in the lab's instruction that can happen and just mention don't worry, just sign in, all roles are set up.

![image](https://user-images.githubusercontent.com/620849/120725229-ba9c3200-c492-11eb-8140-79a9ed2ac060.png)

#shirivo #dp-203

**Comment by ctesta-oneillmsft** [comment]
we have been unable to repro this in our environment, and will forward this to the lab hoster. Thanks

**Comment by shirivo** [comment]
Hello, today 50% of my students got that error.
