### ISSUE TITLE
Module 01 - Explain data

### ISSUE THREAD

**Issue by shirivo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#111]
In my experience, students always ask what each data is. For example, the lab use cell phone accelerometer data but don't explain the schema as is.

![image](https://user-images.githubusercontent.com/620849/120726744-11573b00-c496-11eb-98a1-415f0e0906e1.png)

**Comment by ctesta-oneillmsft** [comment]
The experience we have is mixed. some do ask, most don't, as a result this instruction is by design
