### ISSUE TITLE
Module 02 - Task 1.10

### ISSUE THREAD

**Issue by shirivo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#112]
In the lab, we are working with Azure Data Studio but in task 1.10 says that can see the tables represents in a star schema in a diagram. But Azure Data Studio can't generate diagram, if the students want to replicate, they need to open SSMS instead of Azure Data Studio.

![image](https://user-images.githubusercontent.com/620849/120726948-95112780-c496-11eb-8ac5-9584cdc5afe5.png)

#shirivo #dp-203

**Comment by ctesta-oneillmsft** [comment]
It states in the instructions that the tables would looks as follows, it doesn't attribute the tables being created within Data Studio. The graphic is there as a visual representation

**Comment by shirivo** [comment]
I understood that but the students don't because it's a little confusing. Today I received the same questions from 75% of my class.
