### ISSUE TITLE
Module 02 - 'T' copy shortcut doesn't work as should

### ISSUE THREAD

**Issue by shirivo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#113]
Many times, around the instructions tables, databases names and other where is not need it to copy and paste, the 'T' is available.

For example, here, authentication type has 'T', but this option is a dropdown list.

![image](https://user-images.githubusercontent.com/620849/120727138-02bd5380-c497-11eb-9c00-19f37a5163e4.png)

Other example:

![image](https://user-images.githubusercontent.com/620849/120727352-8d9e4e00-c497-11eb-9f11-d8d32f35e614.png)

Then, I suggest adding here a 'T' for server name:

![image](https://user-images.githubusercontent.com/620849/120727230-3a2c0000-c497-11eb-91ee-5155aceaa77a.png)

![image](https://user-images.githubusercontent.com/620849/120727274-53cd4780-c497-11eb-97c2-a87d89559207.png)

#shirivo #dp-203

**Comment by ctesta-oneillmsft** [comment]
This is an issue with the lab hoster and we cannot resolve this but I have forwarded the message to them
