### ISSUE TITLE
Module 2 Ex5 Task 3 Parameter SQLPool01

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#116]
Module 2 - Design and Implement the serving layer
Exercise 5: Updating slowly changing dimensions with mapping data flows
Task 3: Create a pipeline and run the data flow
Step 9 In the Pipeline run dialog, under Parameters, type the value SQLPool01 under value for the the parameter named DatabaseName, and then click on OK

The SQLPool01 parameter is not available. This step can be removed from the instructions

**Comment by ctesta-oneillmsft** [comment]
resolved
