### ISSUE TITLE
Module 04 - Remove the tasks to setup AAD groups

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#117]
Module 4 - Run interactive queries using serverless SQL pools
Exercise 2: Securing access to data through using a serverless SQL pool in Azure Synapse Analytics

There are a lot of steps to do during Task 1 (Create Azure Active Directory security groups) and Task 2 (Add group members). I believe this should not be part of the data engineering training (as it is more of a security/admin topic). Would it be possible to:

- Automate the creation of these groups/memberships during lab provisioning (so learner doesn't have to do this themselves)
- Remove the steps from the instructions
- Replace by instructions to view/display the setup in AAD

**Comment by ctesta-oneillmsft** [comment]
This is by design as per the exam object which takes up 10 - 15% of the exam

https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4MbYT
