### ISSUE TITLE
Module 17 - screenshot is wrong

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#118]
Module 17: Module 17 - Perform integrated Machine Learning processes in Azure Synapse Analytics
Exercise 1: Create an Azure Machine Learning linked service
Task 2: Explore Azure Machine Learning integration features in Synapse Studio

The screenshot has the red square on the Manage icon. It should be on the Data icon.
![image](https://user-images.githubusercontent.com/53346841/121550441-0741b900-ca0f-11eb-9446-3b393cc70cce.png)

https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure/raw/main/Instructions/Labs/17/media/lab-01-ex-01-task-02-ml-menu.png

**Comment by ctesta-oneillmsft** [comment]
resolved and pushed
