### ISSUE TITLE
Mod 4 Script/Query page goes blank

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#12]
![image](https://user-images.githubusercontent.com/38757647/116371795-19271e00-a80c-11eb-97d7-2d44e6153d6b.png)

I've tried twice to follow these steps:
In the query results, select the Chart view, then configure it as follows:

Chart type: Select Bar.
Category column: Select country_name.
Legend (series) columns: Select population.
Legend position: Select center - bottom.

The query/result of the script, suddenly goes blank as shown in the picture. 
I don't know how this is possible.

**Comment by joelhulen** [comment]
I could not reproduce this problem. It appears to be a transient issue. Next time, try opening a new in-private browser session.
