### ISSUE TITLE
Module 14 - Exercise 2 - Point 7 - TransactionGeneratorExecutable winx64

### ISSUE THREAD

**Issue by annav88** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#123]
Hello everyone!

I was trying to do the Lab14 using the LabOnDemand environment, and when running the TransactionGeneratorExecutable.exe winx64, I get an unhandled exception and the Event Hubs is not sending events.

The error message says **"Unhandled Exception. System.ArgumentNullException: Value cannot be null. (Parameter 'EntityPath')"**. It seems that the TransactionGenerator.Main(String[] args) method cannot the events.

I couldn't check further as I only have the compiled program with .dlls and not the source code.

Please feel free to reach me out if you want to reproduce the issue (or let me know in case if I made something wrong).
I have a screenshot if needed.

Thank you,
Anna

**Comment by joelhulen** [comment]
Hello :)

Did you update the **appsettings.json** per [Exercise 2, Task 1, Step 4](https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure/tree/main/Instructions/Labs/14#task-1-run-data-generator)?

Also, please be sure you're using the connection string from the **write** policy on the `telemetry` event hub, **not** on the event hub namespace (Exercise 1, Task 1, Step 13).

**Comment by annav88** [comment]
Thanks a lot Joel! It was the Event Hubs namespace vs Event Hubs event hub Write policy. That fixed it, sorry for the false alert!
