### ISSUE TITLE
Module 14 - Exercise 1 - Task 3 : Configure Stream Analytics

### ISSUE THREAD

**Issue by annav88** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#124]
In the lab instruction, when setting up the Event Hubs Synapse Analytics output, the instructions say to use SQL dedicated pool's username **asa.sql.admin**, but the user does not exist and during the creation the connection test fails.

In reality, in the Azure Synapse Analytics workspace resource created, I found the SQL dedicated pool username is **m14.asa.sql.admin**.

The below link is the GitHub instruction.

https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure/blob/main/Instructions/Labs/14/media/synapse-new-output.png

Below some screenshots, showing the instructions and the Azure Synapse Analytics username.

![lab14_exercise_01_task_03_001](https://user-images.githubusercontent.com/83666021/122371783-6bf59a00-cf60-11eb-93d1-47cfec662719.png)
![lab14_exercise_01_task_03_002](https://user-images.githubusercontent.com/83666021/122371786-6c8e3080-cf60-11eb-9a08-9194a80c2e4f.png)
![lab14_exercise_01_task_03_003](https://user-images.githubusercontent.com/83666021/122371787-6d26c700-cf60-11eb-84a7-9805375f954b.png)

Thank you!

**Comment by JTomKinser** [comment]
AGREED, but there should be no dot after "m14" in the username. The Username should be entered as "m14asa.sql.admin" instead of just "asa.sql.admin" in the current instructions. Either the instructions need to be changed or the admin Username in Synapse Analytics.

**Comment by annav88** [comment]
The bug has been corrected - I am closing it myself
