### ISSUE TITLE
Lab 2 of Mod 1 Dependencies

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#18]
"Create and configure the Azure Synapse Analytics workspace"
If you deploy the ADB workspace in the resource group where Azure Synapse Analytics is deployed, and don't create a new resource group for the ADB workspace deployment, you don't need to configure the Azure Synapse Analytics workspace. 
It seems there is somehow a dependency.

**Comment by joelhulen** [comment]
This should only be run if you are not using a hosted lab environment. The instructions reflect this in that section.
