### ISSUE TITLE
Mod 1 Lab 1 1-Delta-Architecture Stop Command

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#19]
![image](https://user-images.githubusercontent.com/38757647/116549711-1dc80100-a8f6-11eb-8220-64d8ef717b0d.png)
In the above step, the job keeps going. 
Should we add a step that you manually stop it from running, besides at the end to stop all streams?
I couldn't find that in the commentary and other commands are otherwise waiting to run.

**Comment by joelhulen** [comment]
There is no need to stop this cell. Since it's a streaming job, you can continue executing other cells. In fact, Cell 17 requires this cell (12) to be initialized before you can execute it.
