### ISSUE TITLE
Mod 1 Lab 2 Suffix Issue when Provided Environment. 

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#20]
"Add a new cell to your notebook with the following code (remember to replace <unique_suffix> with the value you specified during the Synapse Analytics workspace deployment):"

There is no unique suffix provided when someone uses a pre-configured environment, in which they shouldn't have to deploy the Synapse Analytics workspace choosing their own suffix. 

When stating: Replace the value below with the name of your primary ADLS Gen2 account for your Synapse workspace, which of these two we mean:
![image](https://user-images.githubusercontent.com/38757647/116551550-5668da00-a8f8-11eb-9cda-893ca0401585.png)

It might cause some confusion. 
Also, what I did was just paste the name of the data lake "asagadatalake<unique_suffix>" and removed, the part of the code where this was mentioned:
 # Replace the value below with the name of your primary ADLS Gen2 account for your Synapse workspace
datalake = 'REPLACE_WITH_YOUR_DATALAKE_NAME'

![image](https://user-images.githubusercontent.com/38757647/116555667-ef015900-a8fc-11eb-82a7-6ec09a31da6d.png)

**Comment by joelhulen** [comment]
Fixed
