### ISSUE TITLE
Mod 1 Lab 2 Set up Synapse Analytics / Notebook

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#21]
"Add a new cell to your notebook with the following code (remember to replace <unique_suffix> with the value you specified during the Synapse Analytics workspace deployment):"

Should we add a step that first you need to create a notebook in which you're going to paste the code?
Or am I missing a step where there should be a notebook in the Azure Synapse Analytics workspace develop area for Mod 1 Lab 2?
I'm using the Azure Synapse Analytics workspace that's been set up in the provided environment.

**Comment by joelhulen** [comment]
I've added these steps.
