### ISSUE TITLE
Query takes long time for Mod 10 Task 3.3

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#24]
IF NOT EXISTS (SELECT * FROM sys.workload_management_workload_groups where name = 'CEODemo')
BEGIN
    Create WORKLOAD GROUP CEODemo WITH  
    ( MIN_PERCENTAGE_RESOURCE = 50        -- integer value
    ,REQUEST_MIN_RESOURCE_GRANT_PERCENT = 25 --  
    ,CAP_PERCENTAGE_RESOURCE = 100
    )
END

This query takes me more than 20 min. Should we add a note, since it takes such a long time and you won't be able to continue with the next SQL script since, this one first needs to finish. After cancelling this query and rerunning it took 5 min.

**Comment by joelhulen** [comment]
Again, this has to do with your environment using a 200 DWU dedicated SQL pool. Please re-run with a 500 DWU size.
