### ISSUE TITLE
Query takes long time for Mod 10 exercise 3 task 1.6

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#25]
![image](https://user-images.githubusercontent.com/38757647/116567511-faa64d00-a907-11eb-8e88-66a208e9a8d2.png)

This query is still running but at the time of the screenshot it took 1 minute instead of 0seconds. 

SELECT TOP 1000 * FROM
(
    SELECT
        S.CustomerId
        ,SUM(S.TotalAmount) as TotalAmount
    FROM
        [wwi_perf].[Sale_Heap] S
    GROUP BY
        S.CustomerId
) T
OPTION (LABEL = 'Lab03: Heap')

**Comment by joelhulen** [comment]
Again, this has to do with your environment using a 200 DWU dedicated SQL pool. Please re-run with a 500 DWU size. Plus, this one had a typo. It should have said **60** seconds.
