### ISSUE TITLE
No results after query in Mod 10 exercise 3 task 1 nr 13 and 14 and 15

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#26]
![image](https://user-images.githubusercontent.com/38757647/116568405-be272100-a908-11eb-99ce-f391c016741a.png)

No results after query: 
SELECT
   *
FROM
    sys.dm_pdw_request_steps
WHERE
    request_id = 'QID6366'
ORDER BY
   step_index

Also no results after the following query in nr 14 and nr 15.

**Comment by joelhulen** [comment]
You were supposed to set the `request_id` to the one you saw in the query before. I updated the instructions to make this clearer.
