### ISSUE TITLE
Query takes >15 min Mod 10 Task 2.4

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#27]
CREATE TABLE [wwi_perf].[Sale_Hash]
WITH
(
   DISTRIBUTION = HASH ( [CustomerId] ),
   CLUSTERED COLUMNSTORE INDEX
)
AS
SELECT
   *
FROM
   [wwi_perf].[Sale_Heap]

This query takes over 15 min in stead of 3.5. minutes for me.

**Comment by joelhulen** [comment]
Updated time count to 10 minutes. Plus, make sure your dedicated SQL pool size is 500 DWUs.
