### ISSUE TITLE
module 4 - Exercise 2 - Task 3 - Resource group name

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#3]
The resource group name to be updated from 

synapse-in-a-day-demos

to 

Synapse-WS-L400-SUFFIX

**Comment by joelhulen** [comment]
Removed the resource group name altogether.

**Comment by joelhulen** [comment]
We don't know what each lab-hosting provider will name the resource group.

**Comment by ctesta-oneillmsft** [comment]
fair comment
