### ISSUE TITLE
Mod 4 Exercise 2 Task 3 number 1

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#41]
![image](https://user-images.githubusercontent.com/38757647/116708000-9353d000-a9cf-11eb-8ae5-095b19bb7fa3.png)

**Comment by joelhulen** [comment]
Removed the resource group name since we don't know what the different lab-host providers will name the resource group.
