### ISSUE TITLE
Mod 7 Exercise 1 Task 3, nr 2

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#48]
![image](https://user-images.githubusercontent.com/38757647/116708399-f5acd080-a9cf-11eb-9f15-5618cf8af139.png)

**Comment by joelhulen** [comment]
The dedicated SQL pool is supposed to be 500 DWUs. The test environment had its size set to 200, which makes these queries run much longer than they should.
