### ISSUE TITLE
Module 7 Exercise 1, Task 2 step 5. 

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#5]
Check the command to discuss options here

**Comment by joelhulen** [comment]
I'm not sure what you're asking here. Can you please elaborate?

**Comment by ctesta-oneillmsft** [comment]
The step states DO NOT RUN
But I think we should get the students to run this command. It takes 14 mins, but we should get them reading the lab wjile it is running. I hope this clears it up
