### ISSUE TITLE
Mod 11, Excersise 1, Task 1, Nr 5

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#52]
The error as seen in the below screenshot, happens, because if you don’t go through module 10, you haven’t created this table, therefore, the object doesn’t exist. 

![image](https://user-images.githubusercontent.com/38757647/116708713-43c1d400-a9d0-11eb-8d4f-809b36ef6424.png)

**Comment by joelhulen** [comment]
Added step to create that table.
