### ISSUE TITLE
Mod 14 Exercise 1, Task 2, Nr 9 and 16

### ISSUE THREAD

**Issue by Kaijisse** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#54]
![image](https://user-images.githubusercontent.com/38757647/116720536-9acda600-a9dc-11eb-8889-70960c312bb8.png)

**Comment by joelhulen** [comment]
This appears to have been a transient error. I was able to successfully create these inputs and outputs, using the provided lab environment.
