### ISSUE TITLE
Module 1, Lab 1, Task 1, lab 01 setup instructions 

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#56]
The first step to setup up the lab, “click the following button to open the ARM template in the Azure Portal” results in an error downloading template.

![deploytoazure](https://user-images.githubusercontent.com/11367710/116763998-7e863500-a9ed-11eb-929a-f769c87c8c0f.png)

Ref:  microsoft-data-engineering-ilt-deploy/lab-01-setup.md at main · solliancenet/microsoft-data-engineering-ilt-deploy (github.com)

**Here is error:**

![errordownloading](https://user-images.githubusercontent.com/11367710/116764058-b55c4b00-a9ed-11eb-849b-1a674e87d922.png)

**Comment by sarbjitsg** [comment]
The steps provided in "Before the hands-on lab" before Lab 1, does not work. Especially with going to this URL and clicking on Deploy to Azure. Does not work. There is a 404 after automatically logging to Azure Portal.

Please fix this step.

Thank You
Sarbjit Singh

**Comment by joelhulen** [comment]
MS recently moved the Azure Databricks ARM template location. I updated the button links.
