### ISSUE TITLE
Module 2 Lab 02: Power BI trial requires a work acount

### ISSUE THREAD

**Issue by sarbjitsg** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#59]
Greetings, 

I am sure the author of the lab is aware the trial Power BI account requires a work account and not a personal Microsoft account. 
I am doing my labs on Azure using a Microsoft Account @ hotmail.com. 

All is well with Azure DevOps, or Azure with this personal account. In Lab 02 for Module 2, i am asked to create a trial Power BI account yet my Synapse Workspace is running using my Azure AD account based on my personal Microsoft Account. The lab setup stops right there for me. It would be useful for me to be able to connect to Power BI as a new Linked Service using a different account than the one i am using to run Synapse. 

Please assist on this issue. 

Thank You 
Sarbjit Singh

**Comment by ctesta-oneillmsft** [comment]
Hi Sarbjit Singh

Hope you are well

These labs have an official environment that is used during the DP-203 course with dedicated accounts and Power BI already setup. We can only support issues in that official environment, and we are unable to assist with custom setups using personal or work accounts.

Thanks 

Chris

cc @joelhulen

**Comment by sarbjitsg** [comment]
Greetings @ctesta-oneillmsft , where is this official environment?  

Thank You 
Sarbjit Singh 

#ps- apologies for the late reply.

**Comment by ctesta-oneillmsft** [comment]
They are provided by a variety of Authorized lab hoster including Spektra, Go-Deploy and Learn on Demand

**Comment by sarbjitsg** [comment]
I checked Go-Deploy and Learn On Demand  does not have the DP-203 labs running yet. Was hoping to try out the labs  on my own Azure subscription using the guides in this repository. Hence the question on Power BI.

Thank You for the reply. 

SS
