### ISSUE TITLE
Rearrange the modules so they are better aligned with the lab environments needed. 

### ISSUE THREAD

**Issue by tibor19** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#62]
Jumping back and forth between lad environments, is a frustrating experience for students, and we should either try to have only one environment, or at least group the modules together, so once done with one environment students don't have to go back to it.

**Comment by ctesta-oneillmsft** [comment]
All the variations you described in your post have been considered. For the training we had to get the balance between cost, impact on instructional design and convenience.

Having one monolithic environment was too expensive. Organizing the modules as you suggest led to a learning path that was disjointed and described as difficult to keep track of the content

Therefore, the option that is provided today is the least disruptive one we have released. It is inconvenient to switch between environments, but no more inconvenient than switching between different VMs, hence the decision point we have today that was validated by a panel of MCT's.

c c @joelhulen
