### ISSUE TITLE
Mod5 Exercise 3 

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#64]
The JSON file that is listed in the cell to read does not exist in the wwi-02 directory. I have looked through all the folder paths and do not see any JSON files in the datastore.

abfss://wwi-02@' + datalake + '.dfs.core.windows.net/online-user-profiles-02/*.json

This prevents the completion of Exercise 4 and 5

**Comment by joelhulen** [comment]
I believe your environment setup failed. You should see the following folders in the `wwi-02` container of the primary data lake storage account, each with files contained within:

![image](https://user-images.githubusercontent.com/5950304/117718131-b50c3e80-b1a9-11eb-8273-8f5ddb3c45bc.png)

I made some improvements to the PowerShell scripts. Please try a new setup by following the instructions here: <https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/tree/main/setup/04>
