### ISSUE TITLE
Mod7 Ex 1, Task 2 and 3

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#65]
Loaded data is listed as 339xxxxxx when after I loaded it, was 340974019.  Is it wise to list a number or should the students just run count queries after each load to see if the results match

**Comment by joelhulen** [comment]
I think perhaps you had issues in your environment setup. I just ran these steps on a brand new environment:

![image](https://user-images.githubusercontent.com/5950304/117715068-c94e3c80-b1a5-11eb-9a53-e802915c02a8.png)

I made some improvements to the PowerShell scripts. Please try a new setup by following the instructions here: <https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/tree/main/setup/04>
