### ISSUE TITLE
Mod 7, Ex 2, Task 1 

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#66]
I loaded this resource group according to instructions and am not seeing these additional SQL Pools as listed. I attached a pic to show what resources were created for this template. I checked the other 2 ASA resource groups I cretaed for the other exercises and they did not have these either.

This also effects future labs as the workspace pools load data for future labs.
![issue pic1](https://user-images.githubusercontent.com/46732841/117553830-57e18300-b019-11eb-8776-4192c63d50dd.png)

**Comment by joelhulen** [comment]
Some steps must have failed during your environment setup. I just completed a fresh deployment and see the following under Linked services:

![image](https://user-images.githubusercontent.com/5950304/117704360-c436c080-b198-11eb-98e4-aa6542f2edbe.png)

I made some improvements to the PowerShell scripts. Please try a new setup by following the instructions here: <https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/tree/main/setup/04>
