### ISSUE TITLE
Mod 8 Ex1, Task 2

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#67]
As with the other issue, I cannot connect to dataset 'online-user-profiles-02' as it does not exist in the wwi-02 file system

**Comment by joelhulen** [comment]
You should see the following folders in the `wwi-02` container:

![image](https://user-images.githubusercontent.com/5950304/117704008-568a9480-b198-11eb-82ce-782f97b13572.png)

I made some improvements to the PowerShell scripts. Please try a new setup by following the instructions here: <https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/tree/main/setup/04>
