### ISSUE TITLE
Mod 13, Task 4, Ex 3

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#69]
This exercise references SQL scripts that are saved for column level, row level and masking exercises. These are not inherently saved in the workspace and there is no reference to an import for these scripts.

**Comment by joelhulen** [comment]
These are loaded by the setup scripts. Something failed during the loading process.

I made some improvements to the PowerShell scripts. Please try a new setup by following the instructions here: <https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/tree/main/setup/04>
