### ISSUE TITLE
Mod 17

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#70]
Lab references an Azure Machine Learning Workspace that was created when deploying the ARM. There is no ML workspace associated with this deployment when I created this resource group's assets.

**Comment by joelhulen** [comment]
Did you run both Part 1 (https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/blob/main/setup/17/asa-workspace-deploy.md) and Part 2 (https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy/blob/main/setup/17/lab-01-deploy.md) for that environment setup? Part 2 deploys an Azure ML workspace.

**Comment by Jason-M-Richards** [comment]
I appreciate all the responses, I am teaching this course in a couple of weeks and am trying to go through the labs so that I can find where students may get hungup. Is there a plan to combine the resources to create one ASA environment to setup rather than splitting this up between three environments? Thats at least two hours of setup when it would be much easier to get everything in one ASA and DB workspace?

**Comment by Jason-M-Richards** [comment]
I appreciate the response and candor. I am testing out one of the lab environments later this week and hope they did a better job of deploying the environments than I did. I look forward to the progress on this and am excited about the direction this course has taken. Thanks for all of the work you put into this.

 

Jason

**Comment by joelhulen** [comment]
My pleasure, Jason. Would you mind telling me which lab environment you are testing? I ran all 16 labs on Spektra's platform (https://cloudlabs.ai/) about a week and a half ago, and it worked flawlessly.

**Comment by Jason-M-Richards** [comment]
I am running it through the cloudlabs.ai platform so I look forward to it. I am told by the training partner that is hosting the course that GoDeploy’s version will be available soon. If there are any other platforms that I can make them aware, please let me know.

 

Jason

**Comment by joelhulen** [comment]
Great. I've been working with GoDeploy a bit. I know they're close. I'll follow up with them today to see where they are in the process.

**Comment by Jason-M-Richards** [comment]
Sorry to bother you Joel,

 

I am going through the CloudLabs setup and did notice that there is a Java package that is not running in the Databricks notebook for module 14? (I cant remember off the top of my head but did post an issue in Github) that was supposed to provided encrypted accesss to event hubs for stream management.

 

I am teaching next week and was wondering if there is a dependency missing or something I may be able to self-resolve if students run into the issue.

 

Thanks,

 

Jason Richards

**Comment by ctesta-oneillmsft** [comment]
closing as the original issue was addressed
