### ISSUE TITLE
Mod 5, Ex 2, Task 13

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#73]
Generally importing all is not a good coding practice since we are not using all of those functions.

from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *

My recommendation: Change the * to the actual functions needed in the block of code.

**Comment by ctesta-oneillmsft** [comment]
The code is set this way by design
