### ISSUE TITLE
Mod 11, Excercise 5, Task 2

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#79]
CTAS query creates table [wwi_perf].[**Sale_Hash_v2**].

Commentary says: "All that would remain to complete the process would be to delete the **Sale_Heap** table and rename **Sale_Heap_v2** to **Sale_Heap**. "

I think **Sale_Hash_v2** should be replaced by **Sale_Heap_v2**

**Comment by ctesta-oneillmsft** [comment]
Changed the statement to:

  The query should execute within about 90 seconds. All that would remain to complete the process would be to delete the original `Sale_Hash` table first, and rename `Sale_Hash_v2` to `Sale_Hash`.
