### ISSUE TITLE
Lab 10 Ex 2

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#86]
The image(s) in Task 2 step 9 and task 3 step 10 show that both workloads should be running. When running the queries, there were suspended status being shown. Was wondering if there was an explanation for that.

![issue](https://user-images.githubusercontent.com/46732841/119237255-85dac300-bb01-11eb-95ad-e79c22a38eb8.png)

**Comment by ctesta-oneillmsft** [comment]
HI @Jason-M-Richards 

We have run this quite a few times in the team, and we did see this behavior once. But on other runs it performed as expected so we are wondering if it is a transient issue. I will close this at the moment as we have had quite a few classes run now and not has this issue raised, if it should return do let us know though
