### ISSUE TITLE
Lab 16, Ex 2, Task 3

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#88]
Like lab 10, tried utilizing the result_set_caching SQL command and it returned a syntax error.

![image](https://user-images.githubusercontent.com/46732841/119241623-79646380-bb1d-11eb-9e1c-21e3b2280797.png)

**Comment by joelhulen** [comment]
Did you connect to the master database?

**Comment by Jason-M-Richards** [comment]
It was connected to the master
