### ISSUE TITLE
Mod 6 - Lab 2 - Missing Exercise 1

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#92]
If Exercise 2 is intended to be the first one please re-sequence the numbering accordingly. Current TOC:

![image](https://user-images.githubusercontent.com/1765732/119739358-f6058380-be36-11eb-9365-aaec80c9441c.png)

**Comment by ctesta-oneillmsft** [comment]
resolved
