### ISSUE TITLE
LODS: Module 06, Exercise 4, Step 9

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#96]
Not a blocking issue, but the verification step fails at the end of Exercise 4. Not sure if this is a permissions issue in the dbfs; or an issue with the lab instructions.

![image1](https://user-images.githubusercontent.com/33545180/119794127-2ac51980-becf-11eb-98bc-3ac8173c526d.jpg)

**Comment by Kaijisse** [comment]
I get the same error. When I go to the solutions file and run that, I get the following error for the same step. @joelhulen could you have a look?
![image](https://user-images.githubusercontent.com/38757647/119810128-0b85b680-bee6-11eb-8dcd-b569a40b5822.png)

**Comment by ctesta-oneillmsft** [comment]
Looks like the file isn't written to be read. Will scrum with @Kaijisse amd @joelhulen to discuss.
