### ISSUE TITLE
LODS: Module 07, Exercise 2, Task 1  Step 8 

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#97]
None of the previous steps failed, but import_01 doesn't appear in the linked services.

**Comment by ctesta-oneillmsft** [comment]
So the linked service is part of the setup, as we are not asked to create this particular linked service. Will sync up with @joelhulen to discuss next steps

**Comment by joelhulen** [comment]
These are the linked services that get created as part of the environment setup, including import_01 (minus the Power BI linked service):

![image](https://user-images.githubusercontent.com/5950304/119825597-1f6cf080-bec5-11eb-94fc-ca6ba51d2f26.png)

**Comment by ctesta-oneillmsft** [comment]
resolved
